// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0BqFzmcH0c2LL96enIQvErZiXuhK9f1I',
    appId: '1:151441918551:web:51a5f56189645e0939f112',
    messagingSenderId: '151441918551',
    projectId: 'fir-test-632021101',
    authDomain: 'fir-test-632021101.firebaseapp.com',
    storageBucket: 'fir-test-632021101.appspot.com',
    measurementId: 'G-J3YEVEX84M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xPFlFiAFP9a_JXWbUGyrJpDRM3abLE0',
    appId: '1:151441918551:android:88b4e602ce96d97f39f112',
    messagingSenderId: '151441918551',
    projectId: 'fir-test-632021101',
    storageBucket: 'fir-test-632021101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGuF0fikS8rZRiiLM_OFhNCkLGG6jBNBs',
    appId: '1:151441918551:ios:ada9a4eb3360c87f39f112',
    messagingSenderId: '151441918551',
    projectId: 'fir-test-632021101',
    storageBucket: 'fir-test-632021101.appspot.com',
    iosClientId: '151441918551-q3elg0jrrvptvin6tvob2d89gk1o7c3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest632021101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGuF0fikS8rZRiiLM_OFhNCkLGG6jBNBs',
    appId: '1:151441918551:ios:ada9a4eb3360c87f39f112',
    messagingSenderId: '151441918551',
    projectId: 'fir-test-632021101',
    storageBucket: 'fir-test-632021101.appspot.com',
    iosClientId: '151441918551-q3elg0jrrvptvin6tvob2d89gk1o7c3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest632021101',
  );
}
